"""Mesh incidence diagnostics. Euler is interpreted only after manifold checks."""
from collections import defaultdict

def inspect_mesh(mesh):
    incident=defaultdict(list); adjacency=defaultdict(set); vertex_faces=defaultdict(set)
    for face in mesh.polygons:
        vs=list(face.vertices)
        for vertex in vs:vertex_faces[vertex].add(face.index)
        for a,b in zip(vs,vs[1:]+vs[:1]):
            key=tuple(sorted((a,b))); incident[key].append(face.index); adjacency[a].add(b); adjacency[b].add(a)
    left=set(range(len(mesh.vertices))); sizes=[]
    while left:
        stack=[left.pop()]; size=0
        while stack:
            v=stack.pop(); size+=1; new=adjacency[v]&left; left-=new; stack.extend(new)
        sizes.append(size)
    def locations(edges):
        return [{'vertices':list(edge),'midpoint_m':[(mesh.vertices[edge[0]].co[i]+mesh.vertices[edge[1]].co[i])*.5 for i in range(3)],'incident_faces':incident[edge]} for edge in edges[:120]]
    boundaries=[e for e,f in incident.items() if len(f)==1]
    nonmanifold=[e for e,f in incident.items() if len(f)>2]
    loose=[tuple(e.vertices) for e in mesh.edges if tuple(sorted(e.vertices)) not in incident]
    split_vertices=[]
    for vertex,faces in vertex_faces.items():
        neighbors=defaultdict(set)
        for other in adjacency[vertex]:
            linked=incident[tuple(sorted((vertex,other)))]
            for face in linked:neighbors[face].update(set(linked)-{face})
        todo=set(faces); fans=0
        while todo:
            fans+=1; stack=[todo.pop()]
            while stack:
                face=stack.pop(); new=neighbors[face]&todo; todo-=new; stack.extend(new)
        if fans>1:split_vertices.append({'vertex':vertex,'position_m':list(mesh.vertices[vertex].co),'face_fans':fans})
    chi=len(mesh.vertices)-len(mesh.edges)+len(mesh.polygons)
    closed=not boundaries and not nonmanifold and not loose and not split_vertices and len(sizes)==1
    genus=(2-chi)/2 if closed else None
    return {'vertices':len(mesh.vertices),'edges':len(mesh.edges),'faces':len(mesh.polygons),'components':len(sizes),'component_vertex_counts':sorted(sizes,reverse=True),'boundary_edge_count':len(boundaries),'nonmanifold_edge_count':len(nonmanifold),'loose_edge_count':len(loose),'nonmanifold_vertex_count':len(split_vertices),'nonmanifold_vertex_locations':split_vertices[:120],'boundary_locations':locations(boundaries),'nonmanifold_locations':locations(nonmanifold),'euler_characteristic':chi,'closed_connected_edge_manifold':closed,'orientable_genus_if_closed':genus,'interpretation':'Genus inference assumes the consistently outward-oriented closed surface generated by this pipeline; Euler alone is not an opening test.'}
