using System;
using UnityEngine;

namespace DesertRV
{
    // Read-only view of authoritative supply facts. Never grants rewards or changes a collider.
    public sealed class JourneySupplyChoiceVisual : MonoBehaviour
    {
        [Serializable] public sealed class Option
        {
            public string id;
            public GameObject availableSign, sealedSign;
        }
        public int region;
        public string choiceGroup;
        public Option[] options = Array.Empty<Option>();
        public GameObject availableBoard, sealedBoard;
        JourneySession journey;

        void LateUpdate()
        {
            if (!journey) journey = FindFirstObjectByType<JourneySession>();
            Refresh(journey ? journey.State : null);
        }
        public void Refresh(SessionState state)
        {
            if (!isActiveAndEnabled || state == null || state.SceneId != region || string.IsNullOrWhiteSpace(choiceGroup)) return;
            bool chosen = state.HasChosenSupplyGroup(choiceGroup);
            if (!availableBoard || !sealedBoard || options == null) return;
            bool changed = availableBoard.activeSelf != !chosen || sealedBoard.activeSelf != chosen;
            foreach (var option in options)
            {
                if (option == null || !option.availableSign || !option.sealedSign) return;
                bool taken = state.HasCollectedSupply(option.id);
                changed |= option.availableSign.activeSelf != (!chosen && !taken) || option.sealedSign.activeSelf != (chosen && !taken);
            }
            if (!changed) return; // No per-frame hierarchy scans, arrays or repeated UI rebuilds.
            // Check the whole binding before changing anything. Presentation cannot disable
            // the business root, its ancestors, a physical object, or another scene's object.
            if (!Decoration(availableBoard) || !Decoration(sealedBoard) || availableBoard == sealedBoard || options == null) return;
            foreach (var option in options)
                if (option == null || string.IsNullOrWhiteSpace(option.id) || !Decoration(option.availableSign) ||
                    !Decoration(option.sealedSign) || option.availableSign == option.sealedSign) return;
            availableBoard.SetActive(!chosen); sealedBoard.SetActive(chosen);
            foreach (var option in options)
            {
                bool taken = state.HasCollectedSupply(option.id);
                option.availableSign.SetActive(!chosen && !taken);
                option.sealedSign.SetActive(chosen && !taken);
            }
        }
        bool Decoration(GameObject value)
        {
            if (!value || value == gameObject || value.scene != gameObject.scene || !value.transform.IsChildOf(transform) ||
                value.GetComponentsInChildren<Collider>(true).Length != 0) return false;
            // Only the exact types generated by SupplySign are presentation. In particular,
            // a collider-free child with a business MonoBehaviour is NOT decoration.
            foreach (var component in value.GetComponentsInChildren<Component>(true))
            {
                if (!component) return false;
                var type = component.GetType();
                if (type != typeof(Transform) && type != typeof(RectTransform) && type != typeof(MeshFilter) &&
                    type != typeof(MeshRenderer) && type != typeof(Canvas) && type != typeof(CanvasRenderer) &&
                    type != typeof(UnityEngine.UI.Text)) return false;
            }
            return true;
        }
    }
}
