using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Rendering;
using Object = UnityEngine.Object;

namespace DesertRV.Editor
{
    public static partial class JourneySceneAuthoring
    {
        const string CorrectedTerrainSha256 = "4fe4e4e5745ce34d4f8eb9668e45a5fab1acf7f6c0baa96de45ae15ff98764a3";
        const string CorrectedTerrainMetaSha256 = "c90d8b8ae8da299cdd47af43312699c27861d72effc9a493c7b142526bd87dd3";
        const string CorrectedTerrainReceipt = "JourneyEvidence/environment-v4-r4/corrected-terrain-report.json";
        static readonly string[] CorrectedTerrainMaterials = {
            PolishGenerated + "/Surface-Sand.mat", PolishGenerated + "/Surface-Dune.mat"
        };
        [Serializable] sealed class CorrectedTerrainImport
        {
            public string assetPath,sha256,metaSha256,guid;
            public int width,height,textureType,textureShape,filterMode,wrapU,wrapV,wrapW,anisoLevel,maxTextureSize,textureCompression,alphaSource;
            public bool sRGBTexture,mipmapEnabled,streamingMipmaps,isReadable,standaloneOverride,androidOverride;
        }
        [Serializable] sealed class CorrectedTerrainFile
        { public string path,beforeSha256,afterSha256; }
        [Serializable] sealed class CorrectedTerrainMaterial
        {
            public string path,originalSerializedBase64,originalSha256,savedSha256,baseMapAsset,baseMapSha256,mainTexAsset,mainTexSha256;
            public bool onlyAlbedoReferencesChanged,secondSaveImportBytesStable;
            public int saveImportCycles;
            public DiffuseComparisonMaterial actual;
        }
        [Serializable] sealed class CorrectedTerrainBinding
        {
            public int region;
            public string objectName,scenePath,meshAsset,materialAsset,baseMapAsset,baseMapSha256,mainTexAsset,mainTexSha256;
        }
        [Serializable] sealed class CorrectedTerrainReport
        {
            public int schema=1,postCaptureImageCount;
            public string status="CORRECTED_TERRAIN_SAVED_NOT_ART_OR_GAMEPLAY_ACCEPTANCE";
            public bool postCaptureVerified,allOtherGeneratedBytesPreserved;
            public CorrectedTerrainImport correctedDiffuse;
            public CorrectedTerrainMaterial[] materials;
            public CorrectedTerrainBinding[] terrainBindings;
            public CorrectedTerrainFile[] generatedFiles;
        }

        // Pure, reusable saved-asset authoring. Historical authoring and both diagnostics stay original.
        public static void AuthorCorrectedTerrainCandidateScenes()
        {
            if(File.Exists(CorrectedTerrainReceipt))throw new IOException("Refuse stale corrected-terrain receipt.");
            var protectedFiles=SnapshotProtectedFiles();
            AuthorCandidateScenes();
            var setup=EditorSceneManager.GetSceneManagerSetup();
            CorrectedTerrainReport report=null;
            try
            {
                EditorSceneManager.OpenScene(BootstrapPath,OpenSceneMode.Single);
                var scene=EditorSceneManager.OpenScene(RegionPaths[0],OpenSceneMode.Additive);
                SceneManager.SetActiveScene(scene);
                FinalizeCorrectedBeaconEmission();
                // First settle Unity's legitimate fresh-material serialization/version normalization.
                // Freeze all generated bytes only after this original-diffuse save/import cycle.
                foreach(string path in CorrectedTerrainMaterials)
                {
                    var material=AssetDatabase.LoadAssetAtPath<Material>(path);
                    if(!material||AssetDatabase.GetAssetPath(material.GetTexture("_BaseMap"))!=ComparisonOriginalDiffuse)
                        throw new InvalidOperationException("Correction must start with newly authored original terrain: "+path);
                    EditorUtility.SetDirty(material);
                }
                AssetDatabase.SaveAssets();
                foreach(string path in CorrectedTerrainMaterials)
                    AssetDatabase.ImportAsset(path,ImportAssetOptions.ForceUpdate|ImportAssetOptions.ForceSynchronousImport);
                AssetDatabase.SaveAssets();
                var before=SnapshotCorrectedTerrainGenerated();
                var records=new List<CorrectedTerrainMaterial>();
                // No asset object is retained across a scene transition. Load after the final OpenScene.
                var corrected=LoadVerifiedCorrectedTerrain(out var importer);
                string originalGuid=AssetDatabase.AssetPathToGUID(ComparisonOriginalDiffuse);
                foreach(string path in CorrectedTerrainMaterials)
                {
                    byte[] original=File.ReadAllBytes(path);
                    var material=AssetDatabase.LoadAssetAtPath<Material>(path);
                    var baseline=new Material(material){hideFlags=HideFlags.HideAndDontSave};
                    try
                    {
                        material.SetTexture("_BaseMap",corrected);material.SetTexture("_MainTex",corrected);
                        AssertCorrectedTerrainMaterial(material,baseline,corrected);
                        EditorUtility.SetDirty(material);AssetDatabase.SaveAssets();
                        AssetDatabase.ImportAsset(path,ImportAssetOptions.ForceUpdate|ImportAssetOptions.ForceSynchronousImport);
                        material=AssetDatabase.LoadAssetAtPath<Material>(path);
                        AssertCorrectedTerrainMaterial(material,baseline,corrected);
                        byte[] firstSaved=File.ReadAllBytes(path);
                        RequireOnlyCorrectedAlbedoReferences(original,firstSaved,originalGuid,importer.guid);
                        // URP synchronizes _MainTex with _BaseMap on material validation. Explicitly persist
                        // both aliases, then prove a second save/import round cannot change any bytes.
                        EditorUtility.SetDirty(material);AssetDatabase.SaveAssets();
                        AssetDatabase.ImportAsset(path,ImportAssetOptions.ForceUpdate|ImportAssetOptions.ForceSynchronousImport);
                        material=AssetDatabase.LoadAssetAtPath<Material>(path);
                        AssertCorrectedTerrainMaterial(material,baseline,corrected);
                        if(!firstSaved.SequenceEqual(File.ReadAllBytes(path)))throw new InvalidOperationException("Corrected material save/import is not byte-stable.");
                        records.Add(new CorrectedTerrainMaterial{path=path,originalSerializedBase64=Convert.ToBase64String(original),
                            originalSha256=before[path],savedSha256=HashFile(path),onlyAlbedoReferencesChanged=true,saveImportCycles=2,secondSaveImportBytesStable=true,
                            baseMapAsset=AssetDatabase.GetAssetPath(material.GetTexture("_BaseMap")),
                            baseMapSha256=HashFile(AssetDatabase.GetAssetPath(material.GetTexture("_BaseMap"))),
                            mainTexAsset=AssetDatabase.GetAssetPath(material.GetTexture("_MainTex")),mainTexSha256=HashFile(AssetDatabase.GetAssetPath(material.GetTexture("_MainTex"))),actual=ReadDiffuseComparisonMaterial(material)});
                    }
                    finally{Object.DestroyImmediate(baseline);}
                }
                var after=SnapshotCorrectedTerrainGenerated();
                RequireCorrectedTerrainGeneratedDelta(before,after);
                report=new CorrectedTerrainReport{correctedDiffuse=importer,materials=records.ToArray(),allOtherGeneratedBytesPreserved=true,
                    generatedFiles=before.Keys.OrderBy(p=>p,StringComparer.Ordinal).Select(p=>new CorrectedTerrainFile{path=p,beforeSha256=before[p],afterSha256=after[p]}).ToArray()};
                report.terrainBindings=ReadSavedCorrectedTerrainBindings(report);
            }
            finally
            {
                try{RestoreSceneSetup(setup);}
                finally{VerifyProtectedFiles(protectedFiles);}
            }
            RequireCorrectedTerrainSavedBytes(report);
            WriteCorrectedTerrainAuditPhase("freeze",report);
            WriteCorrectedTerrainReport(report);
        }

        public static void AuthorAndCaptureCorrectedTerrainCandidates()
        { AuthorCorrectedTerrainCandidateScenes(); JourneyContentChecks.CheckCandidateLayout(); CaptureEnvironmentCandidates(); }

        // The existing single native test calls this after its unchanged 18+2 captures and opaque gates.
        // No static switch, cached Material, second authoring pass, or diagnostic rendering is involved.
        public static void VerifyCorrectedTerrainCandidatesAfterCapture()
        {
            var report=JsonUtility.FromJson<CorrectedTerrainReport>(File.ReadAllText(CorrectedTerrainReceipt));
            if(report==null||report.schema!=1||report.postCaptureVerified||report.postCaptureImageCount!=0)
                throw new InvalidOperationException("Wrong/stale corrected-terrain authoring receipt.");
            RequireCorrectedTerrainSavedBytes(report);
            var setup=EditorSceneManager.GetSceneManagerSetup();var protectedFiles=SnapshotProtectedFiles();
            try
            {
                var bindings=ReadSavedCorrectedTerrainBindings(report);
                if(JsonUtility.ToJson(new CorrectedTerrainReport{terrainBindings=bindings})!=
                   JsonUtility.ToJson(new CorrectedTerrainReport{terrainBindings=report.terrainBindings}))
                    throw new InvalidOperationException("Saved corrected terrain bindings changed across twenty captures.");
            }
            finally{try{RestoreSceneSetup(setup);}finally{VerifyProtectedFiles(protectedFiles);}}
            RequireCorrectedTerrainSavedBytes(report);
            string[] views={"overview","ground","landmark","cabin","motor-driving-editor","motor-walking-editor"};
            var images=RegionPaths.SelectMany(p=>views.Select(v=>"JourneyEvidence/environment/"+Path.GetFileNameWithoutExtension(p)+"-"+v+".png"))
                .Concat(new[]{"JourneyEvidence/environment-v4/FirstStation-forecourt-eye-height.png","JourneyEvidence/environment-v4/FirstStation-garage-eye-height.png"}).ToArray();
            if(images.Length!=20||images.Any(p=>!File.Exists(p)||new FileInfo(p).Length==0))
                throw new InvalidOperationException("The original twenty-camera capture set is incomplete.");
            report.postCaptureImageCount=images.Length;report.postCaptureVerified=true;WriteCorrectedTerrainReport(report);
            WriteCorrectedTerrainAuditPhase("postcapture",report);
            Debug.Log("ENVIRONMENT_V4_R4_CORRECTED saved-two-materials-same-albedo-base-map-main-tex nine-reloaded-terrain-bindings after-twenty-original-views");
        }

        // CORRECTED_BEACON_EMISSION_BEGIN
        // Run 38000418463 proved that only this generated warm diffuser lost _EMISSION after capture.
        // URP 17.3 Lit derives the keyword from GI flags during validation, not from HDR color alone.
        // BakedEmissive records the authored emissive intent; no bake, light, color, or geometry is changed.
        const string CorrectedBeaconMaterial=Folder+"/Layout-FFC261.mat";
        [Serializable] sealed class CorrectedBeaconEmissionEvidence
        {
            public string path,beforeSha256,savedSha256,metaSha256,validator;
            public int beforeGIFlags,afterGIFlags,saveImportCycles=2;
            public bool beforeEmissionKeyword,afterEmissionKeyword,secondSaveStable=true,allNativeObjectsClean=true;
            public Color beforeEmissionColor,afterEmissionColor;
        }
        static Material RequireCorrectedBeaconMaterial(Material material,bool settled)
        {
            if(!material||!EditorUtility.IsPersistent(material)||!AssetDatabase.IsMainAsset(material)||
                AssetDatabase.GetAssetPath(material)!=CorrectedBeaconMaterial||!material.shader||
                material.shader.name!="Universal Render Pipeline/Lit"||!material.shader.isSupported||ShaderUtil.ShaderHasError(material.shader)||
                !material.GetColor("_BaseColor").Equals(new Color(1,.76f,.38f))||
                !material.GetColor("_EmissionColor").Equals(new Color(1,.76f,.38f)*2.5f)||
                material.GetTexture("_EmissionMap")||material.GetTexture("_BaseMap")||
                material.GetFloat("_Smoothness")!=.12f||material.GetFloat("_Metallic")!=0||
                material.GetFloat("_Surface")!=0||material.GetFloat("_ZWrite")!=1||
                material.shaderKeywords.Any(k=>k!="_EMISSION"))
                throw new InvalidOperationException("Warm beacon diffuser lost its exact authored material identity or HDR emission.");
            if(settled&&(material.globalIlluminationFlags!=MaterialGlobalIlluminationFlags.BakedEmissive||
                !material.IsKeywordEnabled("_EMISSION")||EditorUtility.IsDirty(material)))
                throw new InvalidOperationException("Warm beacon emission/GI keyword state is inconsistent or dirty.");
            return material;
        }
        static string ValidateCorrectedBeaconWithInstalledLit(Material material)
        {
            // Use the installed shader's complete validator, including its Lit/detail callbacks.
            // MaterialEditor initializes customShaderGUI in OnEnable; no preview/GUI is rendered.
            var editor=global::UnityEditor.Editor.CreateEditor(material) as MaterialEditor;
            try
            {
                if(!editor||editor.customShaderGUI==null||
                    editor.customShaderGUI.GetType().FullName!="UnityEditor.Rendering.Universal.ShaderGUI.LitShader")
                    throw new InvalidOperationException("Expected the installed URP Lit ShaderGUI validator.");
                editor.customShaderGUI.ValidateMaterial(material);
                return editor.customShaderGUI.GetType().FullName;
            }
            finally{if(editor)Object.DestroyImmediate(editor);}
        }
        static string SettleCorrectedBeaconEmissionCycle()
        {
            var material=RequireCorrectedBeaconMaterial(AssetDatabase.LoadAssetAtPath<Material>(CorrectedBeaconMaterial),false);
            string validator=ValidateCorrectedBeaconWithInstalledLit(material);
            // GUID-level save includes URP's AssetVersion subasset, unlike saving just the main Material.
            AssetDatabase.SaveAssetIfDirty(AssetDatabase.GUIDFromAssetPath(CorrectedBeaconMaterial));
            AssetDatabase.ImportAsset(CorrectedBeaconMaterial,ImportAssetOptions.ForceUpdate|ImportAssetOptions.ForceSynchronousImport);
            AssetDatabase.SaveAssetIfDirty(AssetDatabase.GUIDFromAssetPath(CorrectedBeaconMaterial));
            RequireCorrectedBeaconMaterial(AssetDatabase.LoadAssetAtPath<Material>(CorrectedBeaconMaterial),true);
            var objects=AssetDatabase.LoadAllAssetsAtPath(CorrectedBeaconMaterial);
            if(objects.Length==0||objects.Any(item=>!item||!EditorUtility.IsPersistent(item)||EditorUtility.IsDirty(item)))
                throw new InvalidOperationException("Warm beacon material or native subasset remains dirty after explicit save/import.");
            return validator;
        }
        static string CorrectedBeaconNonEmissionBytes(byte[] bytes)
        {
            if(bytes.Length==0||bytes.Length>65536)throw new InvalidOperationException("Warm beacon material exceeds bounded serialization.");
            string text=new UTF8Encoding(false,true).GetString(bytes);
            var flags=new Regex(@"(?m)^  m_LightmapFlags: [0-7]\r?$",RegexOptions.CultureInvariant);
            var keyword=new Regex(@"(?m)^  m_ValidKeywords:(?: \[\]|\r?\n  - _EMISSION)\r?$",RegexOptions.CultureInvariant);
            if(flags.Matches(text).Count!=1||keyword.Matches(text).Count!=1)
                throw new InvalidOperationException("Missing/ambiguous warm beacon emission fields.");
            // Only these two typed authored fields may change. Version, shader, colors, aliases,
            // textures, passes, render state and every other serialized byte remain compared.
            return keyword.Replace(flags.Replace(text,"  m_LightmapFlags: <authored-emission>"),"  m_ValidKeywords: <authored-emission>");
        }
        static void FinalizeCorrectedBeaconEmission()
        {
            var authored=SnapshotCorrectedTerrainGenerated();byte[] original=File.ReadAllBytes(CorrectedBeaconMaterial);
            string meta=HashFile(CorrectedBeaconMaterial+".meta");
            var material=RequireCorrectedBeaconMaterial(AssetDatabase.LoadAssetAtPath<Material>(CorrectedBeaconMaterial),false);
            int oldFlags=(int)material.globalIlluminationFlags;bool oldKeyword=material.IsKeywordEnabled("_EMISSION");
            Color oldEmission=material.GetColor("_EmissionColor");
            if(material.globalIlluminationFlags!=MaterialGlobalIlluminationFlags.None&&
                material.globalIlluminationFlags!=MaterialGlobalIlluminationFlags.EmissiveIsBlack&&
                material.globalIlluminationFlags!=MaterialGlobalIlluminationFlags.BakedEmissive)
                throw new InvalidOperationException("Refuse to replace an unexpected warm beacon GI mode.");
            // This is the sole authored correction. Keep the original nonzero HDR color unchanged.
            material.globalIlluminationFlags=MaterialGlobalIlluminationFlags.BakedEmissive;
            EditorUtility.SetDirty(material);
            string validator=SettleCorrectedBeaconEmissionCycle();
            byte[] stable=File.ReadAllBytes(CorrectedBeaconMaterial);
            if(CorrectedBeaconNonEmissionBytes(original)!=CorrectedBeaconNonEmissionBytes(stable))
                throw new InvalidOperationException("Warm beacon save changed bytes beyond its GI flag/emission keyword.");
            if(SettleCorrectedBeaconEmissionCycle()!=validator)throw new InvalidOperationException("Installed Lit validator changed between cycles.");
            if(!stable.SequenceEqual(File.ReadAllBytes(CorrectedBeaconMaterial))||HashFile(CorrectedBeaconMaterial+".meta")!=meta)
                throw new InvalidOperationException("Warm beacon material/meta is not stable across two validation/save/import cycles.");
            var settled=SnapshotCorrectedTerrainGenerated();
            if(!authored.Keys.OrderBy(p=>p,StringComparer.Ordinal).SequenceEqual(settled.Keys.OrderBy(p=>p,StringComparer.Ordinal))||authored.Any(row=>row.Key!=CorrectedBeaconMaterial&&settled[row.Key]!=row.Value))
                throw new InvalidOperationException("Warm beacon emission correction changed another generated file.");
            material=RequireCorrectedBeaconMaterial(AssetDatabase.LoadAssetAtPath<Material>(CorrectedBeaconMaterial),true);
            Debug.Log("CORRECTED_BEACON_EMISSION_LIFECYCLE "+JsonUtility.ToJson(new CorrectedBeaconEmissionEvidence{
                path=CorrectedBeaconMaterial,beforeSha256=authored[CorrectedBeaconMaterial],savedSha256=HashFile(CorrectedBeaconMaterial),metaSha256=meta,
                validator=validator,beforeGIFlags=oldFlags,afterGIFlags=(int)material.globalIlluminationFlags,
                beforeEmissionKeyword=oldKeyword,afterEmissionKeyword=material.IsKeywordEnabled("_EMISSION"),beforeEmissionColor=oldEmission,afterEmissionColor=material.GetColor("_EmissionColor")}));
        }
        [Serializable] sealed class CorrectedBeaconEmissionObservation
        {
            public string phase,path,shader;
            public int rendererCount,giFlags=-1,loadedObjectCount,dirtyLoadedObjectCount;
            public bool materialPresent,rendererEnabled,singleMaterial,expectedMaterialIdentity,expectedEmissionColor,expectedGI,emissionKeyword,materialDirty;
            public string[] keywords;
            public Color emissionColor;
        }
        static void RecordCorrectedBeaconEmissionBinding(RegionBinding binding)
        {
            // Observe only: never assert, validate, save, or repair after rendering. An unexpected
            // state must not prevent the existing freeze/postcapture/postexit audit and safe PNG exit.
            // The receipt is created after the author's freeze, so its existence labels this read.
            var row=new CorrectedBeaconEmissionObservation{path=CorrectedBeaconMaterial,
                phase=File.Exists(CorrectedTerrainReceipt)?"postcapture":"author-reload"};
            var renderers=binding.GetComponentsInChildren<Renderer>(true).Where(r=>r.name=="Beacon warm lamp diffuser").ToArray();
            row.rendererCount=renderers.Length;
            if(renderers.Length==1)
            {
                var renderer=renderers[0];row.rendererEnabled=renderer.enabled;row.singleMaterial=renderer.sharedMaterials.Length==1;
                var material=renderer.sharedMaterial;row.materialPresent=material;
                if(material)
                {
                    row.shader=material.shader?material.shader.name:null;
                    row.expectedMaterialIdentity=EditorUtility.IsPersistent(material)&&AssetDatabase.IsMainAsset(material)&&
                        AssetDatabase.GetAssetPath(material)==CorrectedBeaconMaterial&&row.shader=="Universal Render Pipeline/Lit";
                    row.giFlags=(int)material.globalIlluminationFlags;row.expectedGI=material.globalIlluminationFlags==MaterialGlobalIlluminationFlags.BakedEmissive;
                    row.emissionKeyword=material.IsKeywordEnabled("_EMISSION");row.materialDirty=EditorUtility.IsDirty(material);
                    row.keywords=material.shaderKeywords.OrderBy(k=>k,StringComparer.Ordinal).ToArray();
                    if(material.HasProperty("_EmissionColor"))row.emissionColor=material.GetColor("_EmissionColor");
                    row.expectedEmissionColor=row.emissionColor.Equals(new Color(1,.76f,.38f)*2.5f);
                }
            }
            foreach(var item in Resources.FindObjectsOfTypeAll<Object>())
                if(item&&AssetDatabase.GetAssetPath(item)==CorrectedBeaconMaterial)
                {row.loadedObjectCount++;if(EditorUtility.IsDirty(item))row.dirtyLoadedObjectCount++;}
            Debug.Log("CORRECTED_BEACON_EMISSION_OBSERVATION "+JsonUtility.ToJson(row));
        }
        // CORRECTED_BEACON_EMISSION_END

        static Texture2D LoadVerifiedCorrectedTerrain(out CorrectedTerrainImport row)
        {
            var texture=AssetDatabase.LoadAssetAtPath<Texture2D>(ComparisonCorrectedDiffuse);
            var importer=AssetImporter.GetAtPath(ComparisonCorrectedDiffuse) as TextureImporter;
            if(!texture||!importer||HashFile(ComparisonCorrectedDiffuse)!=CorrectedTerrainSha256||HashFile(ComparisonCorrectedDiffuse+".meta")!=CorrectedTerrainMetaSha256||
                texture.width!=1024||texture.height!=1024||texture.mipmapCount<2||texture.filterMode!=FilterMode.Trilinear||
                texture.wrapModeU!=TextureWrapMode.Repeat||texture.wrapModeV!=TextureWrapMode.Repeat||texture.anisoLevel!=4||
                importer.textureType!=TextureImporterType.Default||importer.textureShape!=TextureImporterShape.Texture2D||
                !importer.sRGBTexture||!importer.mipmapEnabled||!importer.streamingMipmaps||importer.isReadable||
                importer.maxTextureSize!=1024||importer.filterMode!=FilterMode.Trilinear||importer.anisoLevel!=4||
                importer.wrapModeU!=TextureWrapMode.Repeat||importer.wrapModeV!=TextureWrapMode.Repeat||importer.wrapModeW!=TextureWrapMode.Repeat||
                importer.alphaSource!=TextureImporterAlphaSource.None||importer.textureCompression!=TextureImporterCompression.Compressed||
                importer.GetPlatformTextureSettings("Standalone").overridden||importer.GetPlatformTextureSettings("Android").overridden)
                throw new InvalidOperationException("Corrected diffuse bytes, imported dimensions, mip/sampler, or import settings differ.");
            row=new CorrectedTerrainImport{assetPath=AssetDatabase.GetAssetPath(texture),sha256=HashFile(ComparisonCorrectedDiffuse),
                metaSha256=HashFile(ComparisonCorrectedDiffuse+".meta"),guid=AssetDatabase.AssetPathToGUID(ComparisonCorrectedDiffuse),
                width=texture.width,height=texture.height,textureType=(int)importer.textureType,textureShape=(int)importer.textureShape,
                sRGBTexture=importer.sRGBTexture,mipmapEnabled=importer.mipmapEnabled,streamingMipmaps=importer.streamingMipmaps,isReadable=importer.isReadable,
                filterMode=(int)importer.filterMode,wrapU=(int)importer.wrapModeU,wrapV=(int)importer.wrapModeV,wrapW=(int)importer.wrapModeW,
                anisoLevel=importer.anisoLevel,maxTextureSize=importer.maxTextureSize,textureCompression=(int)importer.textureCompression,
                alphaSource=(int)importer.alphaSource,standaloneOverride=importer.GetPlatformTextureSettings("Standalone").overridden,
                androidOverride=importer.GetPlatformTextureSettings("Android").overridden};
            return texture;
        }

        static void AssertCorrectedTerrainMaterial(Material material,Material original,Texture2D diffuse)
        {
            if(material.shader!=original.shader||material.renderQueue!=original.renderQueue||material.enableInstancing!=original.enableInstancing||
                material.doubleSidedGI!=original.doubleSidedGI||material.globalIlluminationFlags!=original.globalIlluminationFlags||
                !material.shaderKeywords.OrderBy(k=>k,StringComparer.Ordinal).SequenceEqual(original.shaderKeywords.OrderBy(k=>k,StringComparer.Ordinal))||
                !material.IsKeywordEnabled("_NORMALMAP")||AssetDatabase.GetAssetPath(material.GetTexture("_BumpMap"))!=ComparisonNormal||
                Mathf.Abs(material.GetFloat("_BumpScale")-.035f)>.000001f||material.GetTexture("_BaseMap")!=diffuse||material.GetTexture("_MainTex")!=diffuse)
                throw new InvalidOperationException("Corrected terrain changed shader, keywords, normal, or either albedo alias.");
            for(int i=0;i<original.passCount;i++)
                if(material.GetShaderPassEnabled(original.GetPassName(i))!=original.GetShaderPassEnabled(original.GetPassName(i)))
                    throw new InvalidOperationException("Corrected terrain changed shader pass state.");
            for(int i=0;i<original.shader.GetPropertyCount();i++)
            {
                string property=original.shader.GetPropertyName(i);bool same;
                switch(original.shader.GetPropertyType(i))
                {
                    case ShaderPropertyType.Color:same=material.GetColor(property)==original.GetColor(property);break;
                    case ShaderPropertyType.Vector:same=material.GetVector(property)==original.GetVector(property);break;
                    case ShaderPropertyType.Float:case ShaderPropertyType.Range:same=material.GetFloat(property)==original.GetFloat(property);break;
                    case ShaderPropertyType.Int:same=material.GetInteger(property)==original.GetInteger(property);break;
                    case ShaderPropertyType.Texture:
                        same=material.GetTexture(property)==(property=="_BaseMap"||property=="_MainTex"?diffuse:original.GetTexture(property))&&
                            material.GetTextureScale(property)==original.GetTextureScale(property)&&material.GetTextureOffset(property)==original.GetTextureOffset(property);break;
                    default:throw new InvalidOperationException("Unrecognized corrected terrain shader property: "+property);
                }
                if(!same)throw new InvalidOperationException("Corrected terrain changed material property: "+property);
            }
        }

        static Dictionary<string,string> SnapshotCorrectedTerrainGenerated()
        {
            return Directory.GetFiles(Folder,"*",SearchOption.AllDirectories).Select(p=>p.Replace('\\','/'))
                .Concat(new[]{Folder+".meta"}).OrderBy(p=>p,StringComparer.Ordinal).ToDictionary(p=>p,HashFile);
        }
        static void RequireCorrectedTerrainGeneratedDelta(Dictionary<string,string> before,Dictionary<string,string> after)
        {
            if(!before.Keys.OrderBy(p=>p,StringComparer.Ordinal).SequenceEqual(after.Keys.OrderBy(p=>p,StringComparer.Ordinal)))
                throw new InvalidOperationException("Corrected terrain changed generated asset membership.");
            var changed=before.Keys.Where(p=>before[p]!=after[p]).OrderBy(p=>p,StringComparer.Ordinal).ToArray();
            if(!changed.SequenceEqual(CorrectedTerrainMaterials.OrderBy(p=>p,StringComparer.Ordinal)))
                throw new InvalidOperationException("Only saved Sand/Dune material payloads may change; scenes, meshes, metadata and other materials must be byte-identical.");
        }
        static void RequireOnlyCorrectedAlbedoReferences(byte[] before,byte[] after,string originalGuid,string correctedGuid)
        {
            // Exact UTF-8 bytes: only the two URP albedo-alias GUIDs may differ; every other serialized field is frozen.
            string text=new UTF8Encoding(false,true).GetString(before);
            var pattern=new Regex(@"(?m)^(    - _(BaseMap|MainTex):\r?\n        m_Texture: \{fileID: 2800000, guid: )"+Regex.Escape(originalGuid)+@"(, type: 3\})\r?$",RegexOptions.CultureInvariant);
            if(pattern.Matches(text).Count!=2||pattern.Matches(text).Cast<Match>().Select(m=>m.Groups[2].Value).Distinct().Count()!=2)
                throw new InvalidOperationException("Missing/duplicate original serialized albedo aliases.");
            string expected=pattern.Replace(text,m=>m.Value.Replace(originalGuid,correctedGuid));
            if(!new UTF8Encoding(false,true).GetBytes(expected).SequenceEqual(after))
                throw new InvalidOperationException("A saved material byte other than the two albedo-alias texture GUIDs changed.");
        }
        static CorrectedTerrainBinding[] ReadSavedCorrectedTerrainBindings(CorrectedTerrainReport report)
        {
            var result=new List<CorrectedTerrainBinding>();
            for(int region=1;region<=3;region++)
            {
                EditorSceneManager.OpenScene(BootstrapPath,OpenSceneMode.Single);
                var scene=EditorSceneManager.OpenScene(RegionPaths[region-1],OpenSceneMode.Additive);SceneManager.SetActiveScene(scene);
                // Assets may have been unloaded by OpenScene(Single); reload only after both scene transitions.
                var corrected=LoadVerifiedCorrectedTerrain(out var imported);
                if(JsonUtility.ToJson(imported)!=JsonUtility.ToJson(report.correctedDiffuse))throw new InvalidOperationException("Corrected import identity changed on scene reload.");
                var binding=Components<RegionBinding>(scene).Single();
                if(region==3)RecordCorrectedBeaconEmissionBinding(binding);
                var terrain=binding.GetComponentsInChildren<Renderer>(true).Where(r=>r.enabled&&r.sharedMaterial&&
                    CorrectedTerrainMaterials.Contains(AssetDatabase.GetAssetPath(r.sharedMaterial))).ToArray();
                if(terrain.Length!=3||terrain.Any(r=>r.sharedMaterials.Length!=1))throw new InvalidOperationException("Expected exactly three saved single-material terrain renderers per region.");
                foreach(var role in comparisonTerrainRoles)
                {
                    var renderer=terrain.Single(r=>r.name=="EnvironmentV4 "+role[0]);var mesh=renderer.GetComponent<MeshFilter>();
                    string materialPath=PolishGenerated+"/Surface-"+role[1]+".mat",meshPath=PolishGenerated+"/R"+region+"-"+role[0]+".asset";
                    if(renderer.gameObject.scene!=scene||renderer.transform.parent!=binding.transform||!mesh||!mesh.sharedMesh||
                       AssetDatabase.GetAssetPath(mesh.sharedMesh)!=meshPath||AssetDatabase.GetAssetPath(renderer.sharedMaterial)!=materialPath||
                       renderer.sharedMaterial!=AssetDatabase.LoadAssetAtPath<Material>(materialPath)||renderer.sharedMaterial.GetTexture("_BaseMap")!=corrected||renderer.sharedMaterial.GetTexture("_MainTex")!=corrected)
                        throw new InvalidOperationException("Saved corrected terrain object/parent/scene/mesh/material/BaseMap binding differs.");
                    var expected=report.materials.Single(m=>m.path==materialPath);
                    if(JsonUtility.ToJson(ReadDiffuseComparisonMaterial(renderer.sharedMaterial))!=JsonUtility.ToJson(expected.actual))
                        throw new InvalidOperationException("Persisted terrain material properties differ after scene reload.");
                    result.Add(new CorrectedTerrainBinding{region=region,objectName=renderer.name,scenePath=scene.path,meshAsset=meshPath,
                        materialAsset=materialPath,baseMapAsset=AssetDatabase.GetAssetPath(renderer.sharedMaterial.GetTexture("_BaseMap")),
                        baseMapSha256=HashFile(AssetDatabase.GetAssetPath(renderer.sharedMaterial.GetTexture("_BaseMap"))),
                        mainTexAsset=AssetDatabase.GetAssetPath(renderer.sharedMaterial.GetTexture("_MainTex")),
                        mainTexSha256=HashFile(AssetDatabase.GetAssetPath(renderer.sharedMaterial.GetTexture("_MainTex")))});
                }
            }
            return result.ToArray();
        }
        static void RequireCorrectedTerrainSavedBytes(CorrectedTerrainReport report)
        {
            if(report==null||report.materials==null||report.materials.Length!=2||report.generatedFiles==null||!report.allOtherGeneratedBytesPreserved)
                throw new InvalidOperationException("Incomplete corrected saved-asset receipt.");
            var current=SnapshotCorrectedTerrainGenerated();
            if(!report.generatedFiles.Select(r=>r.path).OrderBy(p=>p,StringComparer.Ordinal).SequenceEqual(current.Keys.OrderBy(p=>p,StringComparer.Ordinal)))
                throw new InvalidOperationException("Generated membership changed after corrected authoring.");
            foreach(var row in report.generatedFiles)
                if(current[row.path]!=row.afterSha256||(!CorrectedTerrainMaterials.Contains(row.path)&&row.beforeSha256!=row.afterSha256))
                    throw new InvalidOperationException("Frozen saved asset changed: "+row.path);
            foreach(var row in report.materials)
            {
                if(!CorrectedTerrainMaterials.Contains(row.path)||!row.onlyAlbedoReferencesChanged||!row.secondSaveImportBytesStable||row.saveImportCycles!=2||HashFile(row.path)!=row.savedSha256)
                    throw new InvalidOperationException("Wrong persisted corrected material identity.");
                RequireOnlyCorrectedAlbedoReferences(Convert.FromBase64String(row.originalSerializedBase64),File.ReadAllBytes(row.path),
                    AssetDatabase.AssetPathToGUID(ComparisonOriginalDiffuse),report.correctedDiffuse.guid);
            }
        }
        [Serializable] sealed class CorrectedTerrainAuditFile
        { public string path,sha256;public long size; }
        [Serializable] sealed class CorrectedTerrainAuditObject
        { public string path,objectType;public long localFileId;public bool hasLocalFileId,isDirty; }
        [Serializable] sealed class CorrectedTerrainAuditPhase
        {
            public int schema=1;public string phase;
            public string observationPolicy="ENUMERATE_ALREADY_LOADED_NO_LOAD_ALL_ASSETS_NO_SAVE";
            public CorrectedTerrainAuditFile[] files;public CorrectedTerrainAuditObject[] loadedObjects;
        }
        static bool IsCorrectedTerrainAuditPath(string path)
        {
            if(path==Folder+".meta"||path==PolishGenerated+".meta")return true;
            string asset=path.EndsWith(".meta",StringComparison.Ordinal)?path.Substring(0,path.Length-5):path;
            if(asset==BootstrapPath||asset==ManifestPath||RegionPaths.Contains(asset))return true;
            if(Regex.IsMatch(asset,"^"+Regex.Escape(Folder)+@"/(?:Region-[123]-Sky|Layout-[A-F0-9]{6})\.mat$"))return true;
            if(polishMaterialNames.Any(name=>asset==PolishGenerated+"/Surface-"+name+".mat"))return true;
            for(int region=1;region<=3;region++)
                if(PolishExpectedMeshNames(region).Any(name=>asset==PolishGenerated+"/R"+region+"-"+name+".asset"))return true;
            return false;
        }
        static void WriteCorrectedTerrainAuditPhase(string phase,CorrectedTerrainReport frozen)
        {
            // Read-only observation: no SaveAssets, imports, scene transitions, or LoadAllAssetsAtPath here.
            if(phase!="freeze"&&phase!="postcapture")throw new InvalidOperationException("Unknown corrected audit phase.");
            const string root="JourneyEvidence/environment-v4-r4-audit";
            string directory=root+"/internal/"+phase;
            if(Directory.Exists(directory)||File.Exists(root+"/"+phase+".json"))throw new IOException("Refuse stale corrected audit phase.");
            var paths=frozen.generatedFiles.Select(r=>r.path).OrderBy(p=>p,StringComparer.Ordinal).ToArray();
            if(paths.Length<=243||paths.Length>=400||paths.Distinct().Count()!=paths.Length||paths.Any(p=>!IsCorrectedTerrainAuditPath(p)))
                throw new InvalidOperationException("Corrected audit path closure rejected.");
            var allowed=new HashSet<string>(paths,StringComparer.Ordinal);
            // FindObjectsOfTypeAll enumerates already-loaded objects only; hidden AssetVersion subobjects
            // are observed without loading any new asset or changing the material validation lifecycle.
            var loaded=new List<CorrectedTerrainAuditObject>();
            foreach(var item in Resources.FindObjectsOfTypeAll<Object>())
            {
                if(!item)continue;string path=AssetDatabase.GetAssetPath(item);
                if(!allowed.Contains(path))continue;
                bool hasLocalId=AssetDatabase.TryGetGUIDAndLocalFileIdentifier(item,out string ignoredGuid,out long localId);
                loaded.Add(new CorrectedTerrainAuditObject{path=path,objectType=item.GetType().FullName,
                    hasLocalFileId=hasLocalId,localFileId=hasLocalId?localId:0,isDirty=EditorUtility.IsDirty(item)});
            }
            var records=new List<CorrectedTerrainAuditFile>();long total=0;
            foreach(string path in paths)
            {
                long size=new FileInfo(path).Length;total+=size;
                if(size<=0||size>40L*1024*1024||total>100L*1024*1024)throw new InvalidOperationException("Corrected audit size limit exceeded.");
                string hash=HashFile(path);
                if(hash!=frozen.generatedFiles.Single(r=>r.path==path).afterSha256)throw new InvalidOperationException("Corrected audit differs from original frozen hash: "+path);
                string copy=directory+"/"+path;Directory.CreateDirectory(Path.GetDirectoryName(copy));File.Copy(path,copy,false);
                if(new FileInfo(copy).Length!=size||HashFile(copy)!=hash||HashFile(path)!=hash)throw new IOException("Corrected audit copy changed bytes: "+path);
                records.Add(new CorrectedTerrainAuditFile{path=path,sha256=hash,size=size});
            }
            var report=new CorrectedTerrainAuditPhase{phase=phase,files=records.ToArray(),loadedObjects=loaded.OrderBy(r=>r.path,StringComparer.Ordinal).ThenBy(r=>r.localFileId).ThenBy(r=>r.objectType,StringComparer.Ordinal).ToArray()};
            string text=JsonUtility.ToJson(report,true),receipt=root+"/"+phase+".json";File.WriteAllText(receipt,text);
            if(File.ReadAllText(receipt)!=text)throw new IOException("Corrected audit phase save failed.");
        }

        static void WriteCorrectedTerrainReport(CorrectedTerrainReport report)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(CorrectedTerrainReceipt));string text=JsonUtility.ToJson(report,true);
            File.WriteAllText(CorrectedTerrainReceipt,text);
            if(File.ReadAllText(CorrectedTerrainReceipt)!=text)throw new IOException("Corrected-terrain receipt save failed.");
        }
    }
}
